'''





Do NOT edit this file unless told to do so by your instructor.









'''


import random

import string
import statistics
import sys

import test_utils
sys.meta_path.append(test_utils.NotebookFinder())
loaded = test_utils.NotebookLoader("./collecting_data.ipynb")
loaded.load_module("collecting_data")

import collecting_data


def test_what_are_topics_you_are_interested_in():
    interest_dict = collecting_data.what_are_topics_you_are_interested_in()
    assert len(interest_dict) != 0, "Your dict is empty!"
    assert len(interest_dict) >= 5, "You do not have enough entries"
    for key, value in interest_dict.items():
        assert len(value.split()) >= 50, f"In dict, {key} does not have 50 words  "

def test_find_some_datasets():
    data_set_dict = collecting_data.find_some_datasets()
    assert len(data_set_dict) != 0, "Your dict is empty"
    assert len(data_set_dict) >=3, "You do not have enough entries"
    for key, value in data_set_dict.items():
        assert type(value) == list, f"Your value is not a list for key: {key}"
        assert len(value) >= 3, f"You need at least 3 urls for key: {key}"